# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: vyos/vyos-build:equuleus
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Clone vyos/vyos-build
      - run: sudo git clone -b equuleus --single-branch https://github.com/vyos/vyos-build /vyos
        
      - name: Build
        run: |
          cd /vyos
          chmod +x $GITHUB_WORKSPACE/build.sh
          sudo $GITHUB_WORKSPACE/build.sh
          
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: /vyos/build/*.iso
