name: Build VyOS

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  VYOS_DEV_CODE: 'equuleus'
  VYOS_VERSION: '1.3.0'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: vyos/vyos-build:${{ env.VYOS_DEV_CODE }}
      options: --privileged

    steps:
      - name: Close this repo
        uses: actions/checkout@v2

      - name: Clone vyos/vyos-build
        uses: actions/checkout@v2
        with:
          repository: vyos/vyos-build
          ref: ${{ env.VYOS_DEV_CODE }}
          path: vyos

      # https://docs.vyos.io/en/latest/contributing/build-vyos.html#build-iso
      # https://tech-mmmm.blogspot.com/2020/05/vyos-12xiso.html
      - name: Build
        run: |
          cd vyos
          ./configure --architecture amd64 --build-type release --version $VYOS_VERSION
          sudo make iso

      # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact-${{ env.VYOS_VERSION }}
          path: vyos/build/vyos-*.iso
