name: Build VyOS

on:
  push:
  workflow_dispatch:

env:
  # You also HAVE TO change container image version.
  VYOS_DEV_CODE: 'sagitta'
  VYOS_VERSION: '1.4.1'

jobs:
  build:
    runs-on: ubuntu-latest

    # Container Settings
    # See: https://docs.vyos.io/en/latest/contributing/build-vyos.html#dockerhub
    container:
      image: vyos/vyos-build:sagitta
      options: --privileged

    steps:
      - name: Close this repo
        uses: actions/checkout@v4

      - name: Clone vyos/vyos-build
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
          ref: ${{ env.VYOS_DEV_CODE }}
          path: vyos

      # https://docs.vyos.io/en/latest/contributing/build-vyos.html#build-iso
      # https://tech-mmmm.blogspot.com/2020/05/vyos-12xiso.html
      - name: Build
        run: |
          cd vyos
          ./build-vyos-image --architecture amd64 --build-type release --version $VYOS_VERSION iso

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Artifact-${{ env.VYOS_VERSION }}
          path: vyos/build/vyos-*.iso
